import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('anyawee_chai@hotmail.com');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('anyawee05');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).press('Enter');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await expect(page.getByRole('heading', { name: '📊 ยินดีต้อนรับสู่ระบบจัดการฐานข้อมูลหลักสูตร' })).toBeVisible();
  await expect(page.getByRole('link', { name: '✏️ แก้ไขประวัติ' })).toBeVisible();
  await page.getByRole('link', { name: '✏️ แก้ไขประวัติ' }).click();
  await page.getByRole('link', { name: '✏️ แก้ไขประวัติ' }).click();
  await page.getByRole('button', { name: ' เลือกรูปโปรไฟล์ใหม่' }).click();
  await page.getByRole('button', { name: ' เลือกรูปโปรไฟล์ใหม่' }).setInputFiles('543019820_1148697490648148_5011506507694356294_n.jpg');
  await page.getByRole('textbox', { name: ' ชื่อ' }).click();
  await page.getByRole('textbox', { name: ' นามสกุล' }).click();
  await page.getByRole('textbox', { name: ' ชื่อ' }).click();
  await page.getByRole('textbox', { name: ' ชื่อ' }).fill('อัญวีณ์');
  await page.getByRole('textbox', { name: ' นามสกุล' }).click();
  await page.getByRole('textbox', { name: ' นามสกุล' }).fill('ไชยวชิระกัมพล');
  await page.getByRole('textbox', { name: ' อีเมล' }).click();
  await page.getByRole('textbox', { name: ' อีเมล' }).fill('anyawee_chai@hotmail.com');
  await page.getByRole('button', { name: ' บันทึกข้อมูล' }).click();
  await page.getByRole('link', { name: '📘 เพิ่มรายวิชา' }).click();
  await page.getByRole('link', { name: '📘 เพิ่มรายวิชา' }).click();
  await expect(page.getByRole('heading', { name: ' เพิ่มรายวิชา' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาไทย' })).toBeVisible();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาไทย' }).click();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาไทย' }).fill('กด');
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาอังกฤษ' }).click();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาอังกฤษ' }).fill('dd');
  await page.locator('#c1').click();
  await page.locator('#c1').fill('1');
  await page.locator('#c2').fill('2');
  await page.locator('#c3').fill('3');
  await page.locator('#c4').fill('5');
  await page.locator('#c5').fill('4');
  await page.locator('#c6').fill('5');
  await page.locator('#c7').fill('2');
  await page.locator('#c8').fill('1');
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).fill('1');
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ราคารายวิชา' }).click();
  await page.getByRole('spinbutton', { name: ' ราคารายวิชา' }).fill('222');
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).click();
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).fill('20');
  await page.getByRole('textbox', { name: ' วันเปิดรายวิชา' }).fill('2025-09-10');
  await page.getByRole('textbox', { name: ' วันปิดรายวิชา' }).fill('2025-09-12');
  await page.getByRole('textbox', { name: ' วันเริ่มรายวิชา' }).fill('2025-09-27');
  await page.locator('div').filter({ hasText: 'วันเปิดรายวิชา' }).nth(4).click();
  await page.getByRole('textbox', { name: ' วันจบเรียนรายวิชา' }).fill('2025-09-27');
  await page.getByRole('textbox', { name: ' รายละเอียดรายวิชา' }).click();
  await page.getByRole('textbox', { name: ' รายละเอียดรายวิชา' }).fill('ssssssssssssssssss');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('543019820_1148697490648148_5011506507694356294_n.jpg');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' บันทึกข้อมูล' }).click();
  await page.locator('select[name="branch_id[]"]').selectOption('10');
  await page.locator('select[name="personnel_id[]"]').selectOption('22');
  await page.getByRole('button', { name: '+ เพิ่มผู้สอน' }).click();
  await page.getByRole('button', { name: ' ลบ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' บันทึกผู้สอน' }).click();
  await page.getByRole('link', { name: '➕ เพิ่มกลุ่มวิชา' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาไทย' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาไทย' }).fill('พ');
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาอังกฤษ' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาอังกฤษ' }).fill('ee');
  await page.locator('#g1').click();
  await page.locator('#g1').fill('1');
  await page.locator('#g2').fill('2');
  await page.locator('#g3').fill('3');
  await page.locator('#g4').fill('4');
  await page.locator('#g5').fill('5');
  await page.locator('#g6').fill('8');
  await page.locator('#g7').fill('2');
  await page.locator('#g8').fill('4');
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).fill('1');
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).fill('1');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).fill('1');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).fill('1');
  await page.getByRole('textbox', { name: ' วันเปิด' }).fill('2025-09-11');
  await page.getByRole('textbox', { name: ' วันปิด' }).fill('2025-09-12');
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).click();
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).fill('5');
  await page.getByRole('spinbutton', { name: ' ราคา (บาท)' }).click();
  await page.getByRole('spinbutton', { name: ' ราคา (บาท)' }).fill('5');
  await page.getByRole('textbox', { name: ' รายละเอียด' }).click();
  await page.getByRole('textbox', { name: ' รายละเอียด' }).fill('555555555');
  await page.getByLabel('ผู้สอน').selectOption('22');
  await page.locator('select[name="course_id[]"]').selectOption('80');
  await page.getByRole('button', { name: '+ เพิ่มคอร์สที่เกี่ยวข้อง' }).click();
  await page.getByText('คอร์สที่เกี่ยวข้อง (เพิ่มได้หลายคอร์ส) -- เลือกคอร์ส --วิทยาการคอมพิวเตอร์พื้นฐา').click();
  await page.getByRole('button', { name: ' ลบ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' บันทึกข้อมูล' }).click();
  await expect(page.getByRole('heading', { name: ' คอร์สเรียนของคุณ' }).locator('span')).toBeVisible();
  await expect(page.getByRole('row', { name: 'พ กด  แก้ไข  โมดูล' }).getByRole('link').first()).toBeVisible();
  await page.getByRole('row', { name: 'พ กด  แก้ไข  โมดูล' }).getByRole('link').first().click();
  await page.getByRole('link', { name: ' ย้อนกลับ' }).click();
  await page.getByRole('row', { name: 'พ กด  แก้ไข  โมดูล' }).getByRole('link').nth(1).click();
  await page.getByRole('link', { name: ' แก้ไข' }).click();
  await page.getByRole('link', { name: ' กลับ' }).click();
  await page.getByRole('link', { name: ' แก้ไข' }).click();
  await page.getByRole('link', { name: ' กลับ' }).click();
  await page.getByRole('link', { name: ' กลับ' }).click();
  await page.getByRole('link', { name: '👨‍🎓 ตรวจสอบการลงทะเบียน' }).click();
  await page.getByRole('link', { name: '👨‍🎓 ตรวจสอบการลงทะเบียน' }).click();
  await expect(page.getByRole('heading', { name: 'รายชื่อนักเรียนที่ลงทะเบียน' })).toBeVisible();
  await page.getByRole('link', { name: '📊 ผลการเรียน' }).click();
  await page.getByRole('link', { name: '📊 ผลการเรียน' }).click();
  await expect(page.getByRole('heading', { name: ' รายชื่อนักเรียน' })).toBeVisible();
  await page.getByRole('link', { name: '🔑 ตั้งรหัสผ่านใหม่' }).click();
  await expect(page.getByRole('textbox', { name: 'รหัสผ่านเดิม' })).toBeVisible();
  await expect(page.getByRole('heading', { name: ' เปลี่ยนรหัสผ่าน' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Profile anyawee_chai@hotmail.' })).toBeVisible();
  await page.getByRole('link', { name: '🏠 หน้าหลัก' }).click();
  await page.getByRole('link', { name: '🏠 หน้าหลัก' }).click();
  await page.getByRole('link', { name: '🚪 ออกจากระบบ' }).click();
});