import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/fornend/');
  await page.getByRole('link', { name: 'สมัครสมาชิก' }).click();
  await page.getByRole('textbox', { name: 'ชื่อ', exact: true }).click();
  await page.getByRole('textbox', { name: 'ชื่อ', exact: true }).fill('ศักดิ์ชัย');
  await page.getByRole('textbox', { name: 'นามสกุล' }).click();
  await page.getByRole('textbox', { name: 'นามสกุล' }).fill('โอษฐงาม');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้' }).fill('sakchai');
  await page.getByRole('textbox', { name: 'รหัสผ่าน', exact: true }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน', exact: true }).fill('007');
  await page.getByRole('textbox', { name: 'ยืนยันรหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'ยืนยันรหัสผ่าน' }).fill('007');
  await page.getByRole('textbox', { name: 'เบอร์โทรศัพท์' }).click();
  await page.getByRole('textbox', { name: 'เบอร์โทรศัพท์' }).fill('0963857491');
  await page.getByRole('textbox', { name: 'อีเมล' }).click();
  await page.getByRole('textbox', { name: 'อีเมล' }).fill('sakchai03@gmail.com');
  await page.getByRole('button', { name: ' สมัครสมาชิก' }).click();
  await expect(page.getByRole('heading', { name: 'กลุ่มวิชาเรียนทั้งหมด' })).toBeVisible();
  await page.getByRole('heading', { name: 'คอร์สเรียนทั้งหมด' }).click();
  await page.getByText('คณะเกษตรศาสตร์และเทคโนโลยี มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน วิทยาเขตสุรินทร์ หน้').click();
  await page.getByRole('link', { name: ' กลุ่มวิชา' }).click();
  await page.getByRole('link', { name: ' รายละเอียด' }).first().click();
  await page.getByRole('link', { name: ' ย้อนกลับ' }).click();
  await page.getByRole('button', { name: ' เพิ่มลงตะกร้า' }).first().click();
  await page.getByRole('link', { name: ' รายวิชา' }).click();
  await page.locator('div:nth-child(3) > .card > .card-body > .d-flex > .btn.btn-primary').click();
  await page.getByRole('link', { name: ' ย้อนกลับ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.locator('div:nth-child(3) > .card > .card-body > .d-flex > .btn.btn-success').click();
  await page.getByRole('link', { name: ' ติดต่อเรา' }).click();
  await expect(page.getByRole('heading', { name: ' ติดต่อเรา' })).toBeVisible();
  await page.getByRole('link', { name: ' ตะกร้าของฉัน' }).click();
  await expect(page.getByRole('heading', { name: '🛒 รายการที่คุณเลือก' })).toBeVisible();
  await page.getByRole('link', { name: ' ชำระเงิน' }).first().click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ชำระเงิน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ชำระเงิน' }).fill('ศักดิ์ชัย');
  await page.getByRole('button', { name: 'แนบหลักฐานการโอนเงิน' }).click();
  await page.getByRole('button', { name: 'แนบหลักฐานการโอนเงิน' }).setInputFiles('_MG_5279.jpg');
  await page.getByRole('button', { name: '✅ ยืนยันการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'กลับหน้าหลัก' }).click();
  await page.getByRole('link', { name: ' ตะกร้าของฉัน' }).click();
  await page.getByRole('button', { name: ' ลบ' }).click();
  await page.getByRole('button', { name: ' ผู้ใช้งาน' }).click();
  await page.getByRole('button', { name: ' ผู้ใช้งาน' }).click();
  await page.getByRole('button', { name: ' ผู้ใช้งาน' }).click();
  await expect(page.getByRole('button', { name: ' ผู้ใช้งาน' })).toBeVisible();
  await page.getByRole('link', { name: ' โปรไฟล์' }).click();
  await page.getByRole('textbox', { name: 'ปล่อยว่างหากไม่เปลี่ยน' }).click();
  await page.getByRole('button', { name: '💾 บันทึกการเปลี่ยนแปลง' }).click();
  await page.getByRole('button', { name: ' ศักดิ์ชัย โอษฐงาม' }).click();
  await expect(page.getByRole('button', { name: ' ศักดิ์ชัย โอษฐงาม' })).toBeVisible();
  await page.getByRole('link', { name: ' คอร์สเรียนของฉัน' }).click();
  await expect(page.getByRole('heading', { name: 'คอร์สของฉัน & เกียรติบัตร' })).toBeVisible();
  await expect(page.getByRole('button', { name: ' ศักดิ์ชัย โอษฐงาม' })).toBeVisible();
});