import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('admin.min');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await expect(page.getByRole('heading', { name: '📊 ยินดีต้อนรับสู่ระบบจัดการฐานข้อมูลหลักสูตร' })).toBeVisible();
  await page.getByText('สามารถจัดการข้อมูลและดูรายงานได้จากหน้านี้').click();
  await expect(page.getByRole('link', { name: '✏️เพิ่มบุคลากร' })).toBeVisible();
  await page.getByRole('link', { name: '✏️เพิ่มบุคลากร' }).click();
  await page.getByRole('link', { name: ' เพิ่มบุคลากรใหม่' }).click();
  await page.locator('input[name="name_ps"]').click();
  await page.locator('input[name="name_ps"]').fill('วิภาสิทธิ์');
  await page.locator('input[name="lastname_ps"]').click();
  await page.locator('input[name="lastname_ps"]').fill('หิรัญรัตน์');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('Wiphasith@hotmail.com');
  await page.locator('select[name="branch_id"]').selectOption('10');
  await page.locator('select[name="position_id"]').selectOption('1');
  await page.locator('select[name="personnelstatus_id"]').selectOption('4');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('wiphasith.jpg');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).fill('Wiphasith@hotmail.com');
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).fill('wiphasith001');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.getByRole('link', { name: '🌿 แก้ไขสาขา' }).click();
  await page.getByRole('link', { name: ' เพิ่มสาขา' }).click();
  await page.getByRole('textbox', { name: 'ชื่อสาขา' }).click();
  await page.getByRole('textbox', { name: 'ชื่อสาขา' }).fill('โยธา');
  await page.getByRole('textbox', { name: 'ชื่อสาขา' }).click();
  await page.getByRole('textbox', { name: 'ชื่อสาขา' }).fill('วิศวะกรรมโยธา');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('row', { name: 'วิศวะกรรมโยธา  แก้ไข  ลบ' }).getByRole('link').nth(1).click();
  await page.getByRole('link', { name: '➕ เพิ่มกลุ่มวิชา' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาไทย' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาไทย' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาไทย' }).fill('ภาษาไทย');
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาอังกฤษ' }).click();
  await page.getByRole('textbox', { name: ' ชื่อกลุ่มวิชาภาษาอังกฤษ' }).fill('thai');
  await page.locator('#g1').click();
  await page.locator('#g1').fill('2');
  await page.locator('#g2').fill('0');
  await page.locator('#g3').fill('0');
  await page.locator('#g4').fill('4');
  await page.locator('#g5').fill('0');
  await page.locator('#g6').fill('0');
  await page.locator('#g7').fill('0');
  await page.locator('#g8').fill('6');
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).fill('7');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).fill('120');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).fill('120');
  await page.getByRole('textbox', { name: ' วันเปิด' }).fill('2025-09-10');
  await page.getByRole('textbox', { name: ' วันปิด' }).fill('2025-09-11');
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).click();
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).fill('20');
  await page.getByRole('spinbutton', { name: ' ราคา (บาท)' }).click();
  await page.getByRole('spinbutton', { name: ' ราคา (บาท)' }).fill('1200');
  await page.getByRole('textbox', { name: ' รายละเอียด' }).click();
  await page.getByRole('textbox', { name: ' รายละเอียด' }).fill('สำหรับดรียนภาษาไทย บทร้อยกรอง ร้อยแก้ว วรรณคดีลำนำ');
  await page.getByRole('textbox', { name: ' รายละเอียด' }).click();
  await page.getByRole('textbox', { name: ' รายละเอียด' }).fill('สำหรับดรียนภาษาไทย บทร้อยกรอง ร้อยแก้ว วรรณคดีลำนำ ');
  await page.getByLabel('ผู้สอน (เจ้าของโมดูล)').selectOption('19');
  await page.locator('select[name="course_id[]"]').selectOption('64');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' บันทึกข้อมูล' }).click();
  await expect(page.getByRole('heading', { name: ' จัดการคอร์สทั้งหมด' })).toBeVisible();
  await expect(page.getByRole('link', { name: '📘 เพิ่มรายวิชา' })).toBeVisible();
  await page.getByRole('link', { name: '📘 เพิ่มรายวิชา' }).dblclick();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาไทย' }).click();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาไทย' }).fill('ภาษาเขมร');
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาอังกฤษ' }).click();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาอังกฤษ' }).fill('kaman');
  await page.locator('#c1').click();
  await page.getByRole('textbox', { name: ' ชื่อรายวิชาภาษาไทย' }).click();
  await page.locator('#c1').click();
  await page.locator('#c1').fill('2');
  await page.locator('#c2').fill('0');
  await page.locator('#c3').fill('0');
  await page.locator('#c4').fill('0');
  await page.locator('#c5').fill('4');
  await page.locator('#c6').fill('0');
  await page.locator('#c7').fill('0');
  await page.locator('#c8').fill('7');
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ทฤษฎี' }).fill('1');
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ปฏิบัติ' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงทฤษฎี' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).click();
  await page.getByRole('spinbutton', { name: ' ชั่วโมงปฏิบัติ' }).fill('2');
  await page.getByRole('spinbutton', { name: ' ราคารายวิชา' }).click();
  await page.getByRole('spinbutton', { name: ' ราคารายวิชา' }).fill('1200');
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).click();
  await page.getByRole('spinbutton', { name: ' จำนวนนักเรียน' }).fill('10');
  await page.getByRole('textbox', { name: ' วันเปิดรายวิชา' }).fill('2025-09-11');
  await page.getByRole('textbox', { name: ' วันปิดรายวิชา' }).fill('2025-09-10');
  await page.getByRole('textbox', { name: ' วันเริ่มรายวิชา' }).fill('2025-09-25');
  await page.getByRole('textbox', { name: ' วันจบเรียนรายวิชา' }).fill('2025-09-23');
  await page.getByRole('textbox', { name: ' รายละเอียดรายวิชา' }).click();
  await page.getByRole('textbox', { name: ' รายละเอียดรายวิชา' }).fill('ใช้สำหรับการสื่อสารภาษา');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('1.jpg');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' บันทึกข้อมูล' }).click();
  await page.locator('select[name="branch_id[]"]').selectOption('10');
  await page.locator('select[name="personnel_id[]"]').selectOption('20');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' บันทึกผู้สอน' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('row', { name: 'บุญเหลือ นาบำรุง (เทคโนโลยีคอมพิวเตอร์) ไม่มีโมดูล ภาษาเขมร  แก้ไข  โมดูล  ลบ' }).getByRole('link').nth(2).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.locator('span').filter({ hasText: 'ภาษาไทย (อนัตต์ชัย ชุติภาสเจริญ)' }).getByRole('link').click();
  await page.getByRole('link', { name: '👨‍🎓 ตรวจสอบการลงทะเบียน' }).click();
  await expect(page.getByRole('heading', { name: ' รายชื่อนักเรียนลงทะเบียน' })).toBeVisible();
  await expect(page.getByRole('button', { name: '' }).first()).toBeVisible();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('link', { name: '📚 ดูคอร์สเรียน' }).click();
  await page.getByRole('link', { name: '📊 รายงานผลการเงิน' }).click();
  await page.getByRole('link', { name: '📊 ผลการเรียน' }).click();
  await expect(page.getByRole('heading', { name: ' รายชื่อนักเรียน' })).toBeVisible();
  await page.getByRole('link', { name: '📊 รายงานผลการเงิน' }).click();
  await expect(page.getByRole('heading', { name: ' รายงานผลการเงิน' })).toBeVisible();
  await page.getByRole('link', { name: '🔑 ตั้งรหัสผ่านใหม่' }).click();
  await page.locator('#current_password').click();
  await page.locator('#current_password').fill('admin.min');
  await page.locator('#new_password').click();
  await page.locator('#new_password').fill('admin');
  await page.locator('#confirm_password').click();
  await page.locator('#confirm_password').fill('admin');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.getByRole('link', { name: 'admin' }).click();
  await page.getByRole('link', { name: '🏠 หน้าหลัก' }).click();
  await page.getByRole('link', { name: 'admin' }).click();
});

